---
- hosts: all
  become: true
  become_method: su
  gather_facts: false
  
  tasks:
    - name: Wait for reachable host
      become: false
      wait_for:
        port: 22
        delay: 5
        connect_timeout: 5
        timeout: 360
        host: "{{ ansible_host }}"
      delegate_to: localhost
 
    - name: Update packages
      raw: apt update

    - name: Update packages
      raw: apt install -y etckeeper

    - name: Now install root wrapper
      raw: apt install -y sudo

    - name: Final greeting
      pause:
        seconds: 1
        echo: false
        prompt: "Minimal setup complete"


