---
- hosts: all
  become: true
  gather_facts: false
  
  tasks:
    - name: Ensure old python2 is no more present
      raw: apt purge -y python2

    - name: As our local Ansible might be too old, install a current one
      raw: apt install -y ansible

