---
- hosts: all
  become: true
  become_method: su
  gather_facts: false
  
  tasks:

    - name: Get the nonprivileged user for sudo
      become: false
      set_fact:
        unprivileged_user: "{{ lookup('env','USER') }}"

    - name: Update packages
      raw: apt update

    - name: First thing to do is to install etckeeper
      raw: apt install -y etckeeper

    - name: Now install root wrapper
      raw: apt install -y sudo

    - name: Allow current user to sudo
      lineinfile:
        path: /etc/sudoers.d/{{ unprivileged_user }}
        line: '{{ unprivileged_user }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: '/usr/sbin/visudo -cf %s'

    - name: Success
      pause:
        seconds: 1
        echo: false
        prompt: |
          Minimal setup complete for {{ unprivileged_user }}
          [OK]

